#!/bin/bash
# Configuration des chemins

BORNE_ROOT="${BORNE_ROOT:-/home/pi/git/borne_arcade}"
MG2D_PATH="${MG2D_PATH:-/home/pi/git/MG2D}"
JAVA_CP="${BORNE_ROOT}:${MG2D_PATH}"

if [ -n "$DEVELOPMENT" ]; then
    BORNE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
    MG2D_PATH="${BORNE_ROOT}/../MG2D"
fi

export BORNE_ROOT
export MG2D_PATH
export JAVA_CP
