#!/bin/bash
# Configuration des chemins

BORNE_ROOT="${BORNE_ROOT:-/home/pi/git/borne_arcade}"
MG2D_JAR="${MG2D_JAR:-/home/pi/git/MG2D.jar}"
JAVA_CP="${BORNE_ROOT}:${MG2D_JAR}"

if [ -n "$DEVELOPMENT" ]; then
    BORNE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
    MG2D_JAR="${BORNE_ROOT}/../MG2D.jar"
fi

export BORNE_ROOT
export MG2D_JAR
export JAVA_CP
